### ISSUE TITLE
Access to csl-gpu7.cs.technion.ac.il

### ISSUE THREAD

**Issue by AdiOmari** [TechnionYP5777/Bugquery#22] opened 2016-12-08 10:29 UTC
Hi @idabran ,

We are having issues accessing csl-gpu7.cs.technion.ac.il (my server) from outside THE technion network (or even the CS faculty network).

I access it through tunneling via out[0,1].cslcs.technion.ac.il, but students don't have access to these machines.  

Thanks,
Adi

**Comment by yossigil** [comment] 2016-12-08 12:40
Create and add a label "blocker".

**Comment by idabran** [comment] 2016-12-11 13:29
Hi @AdiOmari  (and @zvili ),
GPU 7 is dedicated for M.Sc students. We can try to connect it to another subnet in order to let it be in the  B.Sc servers group, and then to ask a permission to access it from outside the Technion.
Is that okay? 
Thanks,
Itai.

**Comment by AdiOmari** [comment] 2016-12-11 16:01
Hi Itai @idabran ,

The machine is mine (no other students, it is bought by eran for me). So this is not an issue. I have already gave them a permission to login with their account (I'm the only admin in gpu7). However, the problem is the access via remote desktop. As I said, we (students, I already have) need access to out[0,1].cslcs.technion.ac.il (not sure if that is what you mean by subnet) in order to use it for tunneling.

This issue is **urgent** (blocker as tagged), please help with the access to the out[0,1].cslcs.technion.ac.il  (or other subnet students can get access to) in order to allow us to proceed.

**Comment by zvili** [comment] 2016-12-11 17:55
@AdiOmari The problem is granting undergraduate students access to csl servers out0 and/or out1.
May I suggest to remove gpu7 from the csl segment and connect it to one of the faculty network segments; and then, follow standard IT procedures to connect from remote.
@idabran FYI.

**Comment by AdiOmari** [comment] 2016-12-12 07:32
I don't think this will help (remote desktop will still be blocked). @zvili Is there any "proxy server"/tunnel server accessible by the undergraduate students? 

@zvili For now please help with the following:
- We want to give the students PHYSICAL access to the csl lap.
- Connect a monitor, keyboard and mouse to my computer.

**Comment by zvili** [comment] 2016-12-12 07:36
@AdiOmari 
No, we will not give the students physical access to the csl lab. It is against our policy.
👎

**Comment by AdiOmari** [comment] 2016-12-12 07:56
1.👎 ??
2. I gave 5 student projects, in all of them I granted them access to the lab?? Also, It is enough to set 3 minutes in the lap to understand that kids who are not even from the faculty have access to it. So what policies are you taking about?
3. The team has at least one MsC student (yonatan zarecki) @yonilx ,  please give him both phyisical and remote (out[0,1].cslcs.technion.ac.il) access to the lap.

**Comment by zvili** [comment] 2016-12-12 08:11
If we are talking about room 232, this is exactly what we are trying to avoid, unauthorized students entering the csl lab.
With respect to grant yonatan access to the lab and opening for him an account in out0/out1, I need a written request from the faculty professor in charge of his MsC degree.

**Comment by AdiOmari** [comment] 2016-12-12 08:25
@yossigil FYI

**Comment by yossigil** [comment] 2016-12-12 20:58
I am not Yontan's advisor...

**Comment by zvili** [comment] 2016-12-13 14:28
@AdiOmari 
I've opened CSL accounts and granted access to the CSL lab (room #232) to: @tonylekhtman @AmitOhayon @ZivIzhar .
I have **not** received the information requested from: @yosefraisman

**Comment by yosefraisman** [comment] 2016-12-13 15:19
Hi @zvili, I sent my information (missed your message from yesterday). Thank you!

**Comment by AdiOmari** [comment] 2016-12-14 01:13
@zvili  Thanks zvi.
@yosefraisman  please remember to close the issue here once you get the access.

**Comment by zvili** [comment] 2016-12-14 06:40
@AdiOmari @yosefraisman : Done.

**Comment by yossigil** [comment] 2016-12-14 08:27
Thanks @zvili

**Comment by yosefraisman** [comment] 2016-12-14 09:37
Thanks again, closing the issue

**Closed by yosefraisman** 2016-12-14 09:37 UTC
Labels: blocker

**Comment by yossigil** [comment] 2016-12-14 09:52
:+1:

**Comment by AmitOhayon** [comment] 2016-12-14 18:47
logged in successfully :)
